### ISSUE TITLE
Не работает авторизация

### ISSUE THREAD

**Issue by aaa4xu** [anilibria/anilibria-docker#6]
https://github.com/anilibria/anilibria/blob/93f9dd4eab2075d148fd62ce3b144e27253ab985/private/init/session.php#L3

Из-за выставленного в `true` аргумента `secure` авторизация возможно только при входе на сайт по `https`. Нужно либо отключить этот флаг в dev окружении, либо написать в инструкцию о генерации своего сертификата.

**Comment by Asethon** [comment]
Добавил генерацию сертификата.

https://github.com/anilibria/anilibria-docker/commit/2fd4049589786f468b21ddbc745af326da446e1b
