### ISSUE TITLE
Не запускается! 

### ISSUE THREAD

**Issue by satanahorror** [anilibria/anilibria-docker#9]
`mariadb_1 | 2020-03-13 17:18:46 0 [Note] Reading of all Master_info entries succeeded

mariadb_1 | 2020-03-13 17:18:46 0 [Note] Added new Master_info '' to hash table

mariadb_1 | 2020-03-13 17:18:46 0 [Note] mysqld: ready for connections.

mariadb_1 | 2020-03-13 17:18:47 8 [Warning] Aborted connection 8 to db: 'anilibria' user: 'anilibria' host: '172.20.0.8' (Got an error reading communication packets)

mariadb_1 | 2020-03-13 17:18:49 9 [Warning] Aborted connection 9 to db: 'anilibria' user: 'anilibria' host: '172.20.0.8' (Got an error reading communication packets)

mariadb_1 | 2020-03-13 17:18:53 10 [Warning] Aborted connection 10 to db: 'anilibria' user: 'anilibria' host: '172.20.0.8' (Got an error reading communication packets)

anilibria-docker-master_sphinx_1 exited with code 1

anilibria-docker-master_xbt_tracker_1 exited with code 1

mariadb_1 | 2020-03-13 17:19:00 11 [Warning] Aborted connection 11 to db: 'anilibria' user: 'anilibria' host: '172.20.0.7' (Got an error reading communication packets)
anilibria-docker-master_sphinx_1 exited with code 1

mariadb_1 | 2020-03-13 17:19:13 12 [Warning] Aborted connection 12 to db: 'anilibria' user: 'anilibria' host: '172.20.0.7' (Got an error reading communication packets)

anilibria-docker-master_sphinx_1 exited with code 1

mariadb_1 | 2020-03-13 17:19:39 13 [Warning] Aborted connection 13 to db: 'anilibria' user: 'anilibria' host: '172.20.0.7' (Got an error reading communication packets)

anilibria-docker-master_sphinx_1 exited with code 1

mariadb_1 | 2020-03-13 17:20:31 14 [Warning] Aborted connection 14 to db: 'anilibria' user: 'anilibria' host: '172.20.0.7' (Got an error reading communication packets)`

Не знаю что делать, помогите!(Делал все по инструкции)

**Comment by Asethon** [comment]
Запустил с на днях накатанной kUbuntu версии 19.10, с установленными git, docker, docker-compose. 
С проблемой не столкнулся. Могли бы вы описать более подробно, что вы делали и на каком именно этапе произошла указанная ошибка?

**Comment by satanahorror** [comment]
Asethon, можно узнать ваши контакты(VK,DISCORD,SKYPE), т.к тут мне не особо удобно писать и т.п

**Comment by Asethon** [comment]
> Asethon, можно узнать ваши контакты(VK,DISCORD,SKYPE), т.к тут мне не особо удобно писать и т.п

VK: https://vk.com/dvk_russie
Telegram: @dvk_russie
